package com.freeorg;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private static final String OUTPUT_FILE = "build/resources/main/outputFile";
	private static final String INPUT_FILE = "inputFile";
	
	public static void main(String[] args) {
		System.out.println(new App().getFile(INPUT_FILE));
	}
	
	private String getFile(String fileName) {

		BufferedWriter bw = null;
		FileWriter fw = null;
		StringBuilder result = new StringBuilder("");
		//Get file from resources folder
		//ClassLoader classLoader = getClass().getClassLoader();
		File file = new File(getClass().getResource(fileName).getFile());
		try (Scanner scanner = new Scanner(file)) {
			fw = new FileWriter(OUTPUT_FILE);
			bw = new BufferedWriter(fw);
			while (scanner.hasNextLine()) {
				String line = scanner.nextLine();
				result.append(line).append("\n");
			}
			bw.write(result.toString());
			scanner.close();
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (bw != null)
					bw.close();
				if (fw != null)
					fw.close();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}
		return result.toString();
	}
	public String getGreeting() {
		return "Hello world.";
	}
}
